drop table if exists user_roles CASCADE;
drop table if exists users CASCADE;
drop table if exists tasks CASCADE;
drop table if exists user_settings CASCADE;

create table user_roles (
user_id bigint not null, roles varchar(255)
);
create table users (
id bigint generated by default as identity, email varchar(255),
first_name varchar(32), last_name varchar(32),
login varchar(32), password varchar(255), primary key (id)
);
create table tasks (
id bigint generated by default as identity, creation_date timestamp, last_modification_date timestamp,
description varchar(4096), status varchar(255), title varchar(255),
assignee_id bigint, author_id bigint, primary key (id)
);
create table user_settings (
user_id bigint not null, preferred_locale varchar(2), primary key (user_id)
);

alter table users add constraint email_value_constraint unique (email);
alter table users add constraint login_value_constraint unique (login);
alter table tasks add constraint assignee_foreign_key_constraint foreign key (assignee_id) references users;
alter table tasks add constraint author_foreign_key_constraint foreign key (author_id) references users;
alter table user_roles add constraint user_roles_foreign_key_constraint foreign key (user_id) references users;
alter table user_settings add constraint user_settings_foreign_key_constraint foreign key (user_id) references users
